### PR TITLE
fix(exports): update types path to use the correct type def

### LINKED ISSUE #143: [Bug]: Imports are broken after upgrade to 3.1.4
In 3.1.4 exports are broken:

```typescript
 import { Bar } from "svelte-chartjs";
```

> Error: Module '"svelte-chartjs"' has no exported member 'Bar'. (ts)

### Reproduction

Create new SvelteKit project.
Install svelte-chartjs version 3.1.4.
Add import from svelte-chartjs (as shown above) to one of your .svelte files.
Run `npm run svelte-check`.

### chart.js version

4.4.1

### svelte-chartjs version

3.1.4

### Possible solution

This amend to "exports" section of package.json fixes the issue (but I`m not 100% sure it is the right way of fixing this):
```json
  "exports": {
    ".": {
      "types": "./dist/index.d.ts",
     ...
    }
}
```

### PR DESCRIPTION
**Pull request by dysfunc**
Updates the `types` export path to use the correct type def file

Fixes #143

### CODE REVIEW

**Comment by dysfunc** [comment]
@niemyjski we should this merged and release another version so types work properly

**Comment by vancityliam** [comment]
Thanks for fixing this. Do you know when the new version will be available?

**Comment by niemyjski** [comment]
Thanks for the PR!, I'll push out a new release now

**Comment by niemyjski** [comment]
Release has been created!

**Comment by avi12** [comment]
After updating to [3.1.5](https://github.com/SauravKanchan/svelte-chartjs/releases/tag/v3.1.5) I still run into #143

**Comment by niemyjski** [comment]
@avi12 please create a pr for this and please open a new issue with the logs. Please also make sure your dependencies / toolchain is up to date.

**Pull request merged**
